# Generated by Django 4.2.25 on 2025-10-16 08:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('800.00'), max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash_deposit', 'Cash Deposit'), ('telebirr', 'TeleBirr'), ('cbe_birr', 'CBE Birr'), ('other', 'Other')], max_length=20)),
                ('payment_proof', models.ImageField(help_text='Upload screenshot or photo of payment receipt', upload_to='payment_proofs/')),
                ('transaction_id', models.CharField(blank=True, help_text='Bank/Mobile transaction ID', max_length=200)),
                ('sender_name', models.CharField(help_text='Name of person who made the payment', max_length=200)),
                ('sender_phone', models.CharField(blank=True, help_text='Phone number used for payment', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applications.dvapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash_deposit', 'Cash Deposit'), ('telebirr', 'TeleBirr'), ('cbe_birr', 'CBE Birr')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('account_details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('refund_processed', 'Refund Processed')], max_length=50)),
                ('message', models.TextField()),
                ('sent_via_telegram', models.BooleanField(default=False)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payments.payment')),
            ],
        ),
    ]
