# Generated by Django 4.2.25 on 2025-10-16 09:57

import applications.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_id', models.CharField(default=applications.models.generate_dv_id, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('city_of_birth', models.CharField(max_length=100)),
                ('country_of_birth', models.CharField(max_length=100)),
                ('country_of_citizenship', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('education_level', models.CharField(choices=[('primary', 'Primary School Only'), ('secondary', 'High School, No Degree'), ('vocational', 'Vocational School'), ('university', 'University Degree'), ('graduate', 'Graduate Degree'), ('doctorate', 'Doctorate Degree')], max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single, Never Married'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Legally Separated')], max_length=20)),
                ('photo', models.ImageField(upload_to='applicant_photos/%Y/%m/')),
                ('payment_proof', models.ImageField(upload_to='payment_proofs/%Y/%m/')),
                ('payment_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_validation_passed', models.BooleanField(default=False)),
                ('photo_validation_message', models.TextField(blank=True, null=True)),
                ('data_validation_passed', models.BooleanField(default=False)),
                ('data_validation_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DVSpouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('city_of_birth', models.CharField(max_length=100)),
                ('country_of_birth', models.CharField(max_length=100)),
                ('country_of_citizenship', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='spouse_photos/%Y/%m/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='applications.dvapplication')),
            ],
        ),
        migrations.CreateModel(
            name='DVChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('city_of_birth', models.CharField(max_length=100)),
                ('country_of_birth', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='child_photos/%Y/%m/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='applications.dvapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='applications.dvapplication')),
            ],
            options={
                'verbose_name_plural': 'Application Statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
